INSERT INTO [dbo].[Address] (City, Street, HouseNumber)
VALUES 
('Tel Aviv', 'Aben Gurio', 1),
('Jerusalem', 'Ben Yehud', 2),
('Haifa', 'Presid', 3),
('Holon', 'Indep', 4),
('Bat Yam', 'Shderot', 5),
('Rishon', 'Herzl', 6),
('Ramla', 'Shderot', 7),
('Netanya', 'David H', 8),
('Petah Tik', 'Chaim W', 9),
('Ashdod', 'The Port', 10),
('Afula', 'The Vine', 11),
('Kiryat Sh', 'The Peace', 12),
('Tiberias', 'The Kinn', 13),
('Eilat', 'Red Sea', 14),
('Modi''in', 'Oren', 15),
('Ma''alot', 'Cypress', 16),
('Kfar Sab', 'The Golan', 17),
('Ra''anana', 'The Herm', 18),
('Zichron Y', 'The Car', 19),
('Shoham', 'Energy', 20),
('Savyon', 'President', 21),
('Mezkeret', 'The Life', 22),
('Nes Tzion', 'Knesset', 23),
('Beersheba', 'Streams', 24),
('Or Yehud', 'The Tamar', 25),
('Yeruham', 'The Work', 26),
('Sderot', 'The Life', 27),
('Dimona', 'The Peace', 28),
('Kiryat G', 'The Life', 29),
('Netivot', 'The Life', 30);
